### ISSUE TITLE
Uncaught TypeError: Cannot read properties of undefined (reading 'children')

### ISSUE THREAD

**Issue by linonetwo** [felixhayashi/TW5-HotZone#5]
```
            var l = function() {
                    var r = $tw.wiki.getTiddler("$:/StoryList");
                    if (r && r.fields.list.length) {
                        var l = null;
                        var o = Number.MAX_VALUE;
                        var f = i.children;
                        var u = t.classNames.tiddlerFrame;
```

var f = i.children; // here

When opening wiki whth calendar layout opened.

**Comment by linonetwo** [comment]
Uncaught TypeError: Cannot read properties of undefined (reading 'children')
    at l (hotzone.js:10:1068)
    at eval (hotzone.js:10:1521)

![图片](https://github.com/felixhayashi/TW5-HotZone/assets/3746270/ec4dea78-7965-45d8-98dd-74f532d62ae3)
